#!/usr/bin/env node
/* ============================================================================
   render-privacy — write the README's privacy section from privacy.json.

   10-WEBSITE §5: /privacy is "generated from one source shared with the README
   and the app's settings screen; the build fails if the three disagree." This
   script is the README half. The site page reads the same file directly at
   build time, and site/scripts/gates.mjs asserts the rendered page still
   contains every section of it.

   Three hand-maintained copies of a privacy statement are three statements that
   will disagree, and this is the document where that matters most — so no
   surface is written by hand.

     node release/render-privacy.mjs          # rewrite the block
     node release/render-privacy.mjs --check  # fail if it is stale

   The block is delimited by HTML comments so the rest of README.md is untouched.
   ========================================================================== */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BEGIN = '<!-- BEGIN GENERATED: privacy.json -->';
const END = '<!-- END GENERATED: privacy.json -->';

const src = JSON.parse(readFileSync(join(ROOT, 'release', 'privacy.json'), 'utf8'));

const body = [
  BEGIN,
  '',
  '<!-- Generated by release/render-privacy.mjs. Edit release/privacy.json, not this. -->',
  '',
  '## Privacy',
  '',
  `Under ${src.word_cap} words, and the same words the site and the app's settings screen show.`,
  '',
  ...src.sections.flatMap((s) => [`**${s.heading}.** ${s.body}`, '']),
  `*${src.closing}*`,
  '',
  END,
].join('\n');

const path = join(ROOT, 'README.md');
const readme = readFileSync(path, 'utf8');

const start = readme.indexOf(BEGIN);
const stop = readme.indexOf(END);

let next;
if (start >= 0 && stop > start) {
  next = readme.slice(0, start) + body + readme.slice(stop + END.length);
} else if (start >= 0 || stop >= 0) {
  console.error('  README.md has one delimiter and not the other — refusing to guess.');
  process.exit(1);
} else {
  // First run: place it before the final horizontal rule so it reads as a
  // section rather than an appendix.
  const at = readme.lastIndexOf('\n---\n');
  next = at < 0 ? readme.trimEnd() + '\n\n---\n\n' + body + '\n' : readme.slice(0, at + 1) + '\n' + body + '\n' + readme.slice(at + 1);
}

if (process.argv.includes('--check')) {
  if (next === readme) {
    console.log('  README privacy section matches privacy.json');
    process.exit(0);
  }
  console.error('  README privacy section is stale — run `node release/render-privacy.mjs`');
  process.exit(1);
}

writeFileSync(path, next, 'utf8');
console.log(`  README privacy section written from privacy.json (${src.sections.length} sections)`);
